title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
    - go mod tidy
    - go mod vendor
    - find . -name ".DS_Store" -print -delete
    - gofmt -w ./
  after:
  - echo "zzz end"
  exit:
  - echo "exit"
link: https://github.com/midoks/zzz
