title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- scripts
- vendor
- logs
- templates
- custom
ext:
- go
- tmpl
enablerun: true
action:
  before:
    # - go mod tidy
    # - go mod vendor
    - find . -name ".DS_Store" -print -delete
    - gofmt -w ./
    - ps -ef|grep 'ndm web'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
    - ./ndm web &
  exit:
    - ps -ef|grep 'ndm web'| grep -v grep | awk '{print $2}' | xargs kill -9
    - rm -rf ./ndm
link: https://github.com/midoks/zzz
