title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- scripts
- vendor
- logs
- templates
ext:
- go
- tmpl
enablerun: true
action:
  before:
    - go mod tidy
    - go mod vendor
    - taskkill /F /im ndm.exe
  after:
    - .\ndm web &
  exit:
    - taskkill /F /im ndm.exe
link: https://github.com/midoks/zzz
